project:
  type: website
  output-dir: docs


website:
  title: "CSC 130"
  sidebar:
    collapsible: true
    search: true
    contents:      
      - text: Home
        href: "practice/index.qmd"
      - section: "Practice"
        contents:
          - text: Problem 1
            href: "practice/problem1.qmd"
          - text: Problem 2
            href: "practice/problem2.qmd"
          - text: Problem 3
            href: "practice/problem3.qmd"
          - text: Problem 4
            href: "practice/problem4.qmd"
      - section: "Pi Activities"
        contents:
          - text: Alarm System
            href: "pi activities/05/instructions.qmd"



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




